# Generated by Django 5.2.6 on 2025-09-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_diary', '0002_schoolclass_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
