# Generated by Django 5.2.6 on 2025-10-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Пройшов', 'Пройшов'), ('Проходить', 'Проходить'), ('Буде проходити', 'Буде проходити')], default='Буде проходити', max_length=50),
        ),
    ]
