# Generated by Django 5.2.6 on 2025-09-28 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('electronic_diary', '0002_schoolclass_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='electronic_diary.schoolclass'),
        ),
    ]
