# Generated by Django 5.2.6 on 2025-10-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_diary', '0003_diaryentry_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mon', 'Понеділок'), ('tue', 'Вівторок'), ('wed', 'Середа'), ('thu', 'Четвер'), ('fri', 'П’ятниця'), ('sat', 'Субота')], max_length=10)),
                ('lesson_number', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diary.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diary.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronic_diary.teacher')),
            ],
        ),
    ]
